Adding check constraints to an existing database
Lesson: this could cause a rails migration to fail when the existing
records do not adhere to the new constraint.

What happened: there were two exisiting records in the database. After
applying the migration to add email constraints, the migration failed to
execute.

The Error:
-- execute(" ALTER TABLE users ADD CONSTRAINT\n
email_must_be_company_issued\n
CHECK (email ~* '^[^@]+@example\\.com$');\n    ")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::CheckViolation: ERROR:  check constraint "email_must_be_company_issued" is violated by some row
(app directory)/20210222174220_add_email_contraint_to_users.rb:3:in `up'

The Resolution:
admin$ rails dbconsole
psql (13.1, server 9.5.22)
Type "help" for help.

development=# UPDATE users SET email = 'test@example.com' WHERE id =2;
UPDATE 1
development=# UPDATE users SET email = 'user@example.com' WHERE id =1;
UPDATE 1
development=# \q
admin$ rake db:migrate
== 20210222174220 AddEmailContraintToUsers: migrating =========================
-- execute(" ALTER TABLE users ADD CONSTRAINT\n
email_must_be_company_issued\n
CHECK (email ~* '^[^@]+@example\\.com$');\n    ")
   -> 0.0073s
== 20210222174220 AddEmailContraintToUsers: migrated (0.0075s) ================